class SaveValue:
    #存储全局变量
    TOKEN = None
    TOKEN_C = None

    COOKIES_F = None

    COOKIES_WC = None

    HEADER = {'Content-Type': 'application/json'}

    COOKIES = None

    REGTIME = None

    MEMBER_ID = None

    AMOUNT = None

    SESSION = None

    TEST_CASE_ZHIFENG_TEST_CREATINVENTORY = None

    TOKEN_U = None

    TOKEN_V = None

    SHOP_TOKEN = None

    SHOP_AUTHRIZATION = None

    TOKEN_FEN = None

    TOKEN_FONT = None

    TOKEN_wxappF = 'eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOm51bGwsImF1ZCI6IjEwMSIsInN1YiI6IjU4MWMwMGUxMmE1MGYwZmYwNzVlNGYyOSIsImFwcGlkIjoiMTAxIiwiZXhwIjoxNTY2OTU2MDA1LCJqdGkiOiI5ZVlXVVVPZVgyZXAxZ3ZCZjBjTHNBIiwiaWF0IjoxNTY2MzUxMjA1LCJhdXRoX21vZGUiOiJtb2JpbGUiLCJhdXRoX2lkIjoiKzg2LTEzNjc2MDU1NzE5In0.Nwl-ud4Gk7LL8kzOWOSkQnD4o8vk3j7mkK8TWx9bSaM'

    TOKEN_wxappV = 'eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOm51bGwsImF1ZCI6IjEwMSIsInN1YiI6IjVhY2VjNThhZWM2OGE4NGJjN2MxYjQ5NSIsImFwcGlkIjoiMTAxIiwiZXhwIjoxNTg0MDc3ODM4LCJqdGkiOiJtMHpaWVRlbGtZMFp5RWpLUm9WY1dRIiwiaWF0IjoxNTgzNDczMDM4LCJhdXRoX21vZGUiOiJtb2JpbGUiLCJhdXRoX2lkIjoiKzg2LTEzNjQwOTkzNTEzIn0.7ScpJMJpUWDg8ZRCRddQ9MOzGFHXExsWL6guUeGCAKs'

    F_UUID = None

    C_UUID = None

    V_UUID = '444'